### PR TITLE
Added a 'switch' command to just turn a plug on or off.

### PR DESCRIPTION
**Pull request by OpinionatedGeek**
Hi,

I wanted a way to turn my plug on or off, but none of the Energenie code samples worked in my situation so I was directed here.

I pulled some of the code from monitor.py into a new file and added some command-line parameter handling so that it can take a device ID and a state.

I run the command simply as:
    sudo python switch.py --name 0xABC --action on

(Where 'name' is the device ID in hex and 'action' is either 'on' or 'off'.)

I didn't try to centralise any common code between this and monitor.py. I figured you probably had a plan for this and I didn't want to interfere. It does mean there's some duplication though.

I'd expected the plug to send a response or acknowledgement of current state, but I'm not seeing one. Maybe I'm doing something wrong. I'd like it to be able to verify the command was received but I'm not sure how to do that.

This is enough to get me turning the plug on or off on a schedule. I don't know if it's of any use to you, but I figured I'd pass it along.

Many thanks,

```
Geoff
```

### CODE REVIEW

**Comment by PatchworkBoy** [comment]
There is no verification unless you have the MiHome Monitor or MiHome Adapter Plus (purple branded sockets with white switch). The older / other sockets are “dumb” - no replies/validation.

**Comment by OpinionatedGeek** [comment]
The code was written for an Energenie MIHO005 Adapter Plus using an Energenie ENER314-RT Pi-Mote. I've had no luck getting my Pi2 to work with the Energenie ENER002-2PI and green plugs.

**Comment by PatchworkBoy** [comment]
https://github.com/whaleygeek/pyenergenie/issues/23 covers ENER314-RT with ENER002 green plugs.

**Comment by OpinionatedGeek** [comment]
Two quick things:

1. I updated the switch command to take a parameter '--device' instead of '--name', since it takes a device ID. The device ID should work if it's specified in decimal, or in hex if it has an 0x prefix. I like the idea of having friendly names for devices, but I haven't tackled that yet.
2. The code is running just fine on my Raspberry Pi 3 - thanks for that!

**Comment by whaleygeek** [comment]
Good work. 

However, since you did this change, I have mostly 'finished' the upstairs abstraction logic, which makes it easy to do these sorts of little applications without even needing to interact with the OpenHEMS packetizer directly any more.  It also means that sockets both from the legacy OOK and the new FSK(MiHome) range can be used interchangeably via the new device-class abstractions.

There are some examples in the src directory that show how you can switch plugs on and off in a very abstract way, with or without using the new device registry.

Thanks for the pull request, but things have moved on a lot since then, so I'll close this down.

**Pull request closed without merging**
